portfolio/portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('reggioio/', admin.site.urls),
    path('', include('portfolio_landing.urls')),

]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ]+urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/portfolio_landing/urls.py
from .views import index, cv_page, index_fr, cv_page_fr, index_rus, cv_page_rus, certificates

from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('', index, name='index'),
    path('cv/', cv_page, name='cv_page'),
    path('certificates/', certificates, name='certificates'),
    path('lang/fr/', index_fr, name='index_fr'),
    path('lang/fr/cv/', cv_page_fr, name='cv_page_fr'),
    path('lang/rus/', index_rus, name='index_rus'),
    path('lang/rus/cv/', cv_page_rus, name='cv_page_rus'),

]

portfolio/portfolio_landing/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
# CV:
# Language
# Skills
# Experience
# Interest
# Contact
# Profile Picture
####################
##### Portfolio #####
# Services (Title, Icon)
# Works (Title, Icon, Description)
# About_me (general description, photo)
# Introduction (General description, photo)
# telepram settings




###########################PORTFOLIO#########################

page_language_choices = (
    ("ENG", "ENG"),
    ("FR", "FR"),
    ("RUS","RUS"),
    ("IT","IT"),)

class Service(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    ordering_rate = models.IntegerField(default=1, verbose_name='ordering', validators=[MinValueValidator(1),
                                                                                           MaxValueValidator(100)])
    description = models.TextField(blank=True)
    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    photo = models.ImageField(upload_to=f'photos/{title}', verbose_name='Img', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Published')

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-title']

    def get_absolute_url(self):
        return reverse('service',kwargs={"slug":self.slug})

class Work(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    work_title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    ordering_rate = models.IntegerField(default=1, verbose_name='ordering', validators=[MinValueValidator(1),
                                                                                   MaxValueValidator(100)])
    work_link = models.TextField(blank=True)
    work_description = models.TextField(blank=True)
    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    work_photo = models.ImageField(upload_to=f'photos/{work_title}', verbose_name='Img', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Published')

    def __str__(self):
        return self.work_title

    class Meta:
        ordering = ['-work_title']

    def get_absolute_url(self):
        return reverse('work',kwargs={"slug":self.slug})

class AboutMe(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    myname = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)

    aboutmetitle = models.TextField(blank=True)
    description = models.TextField(blank=True)

    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    my_photo = models.ImageField(upload_to=f'photos/{myname}', verbose_name='Img', blank=True)

    def __str__(self):
        return self.myname

    class Meta:
        ordering = ['-myname']

    def get_absolute_url(self):
        return reverse('aboutme',kwargs={"slug":self.slug})

class Cvdata(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    mycvname = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    cvmail = models.CharField(max_length=100)
    cvlocation = models.CharField(max_length=100)
    cvlinkedin = models.CharField(max_length=100)
    cvwebsite = models.CharField(max_length=300)
    myprofile = models.TextField(blank=True)
    description = models.TextField(blank=True)
    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    my_cv_photo = models.ImageField(upload_to=f'photos/{mycvname}', verbose_name='Img', blank=True)

    def __str__(self):
        return self.mycvname

    class Meta:
        ordering = ['-mycvname']

    def get_absolute_url(self):
        return reverse('cvdata',kwargs={"slug":self.slug})


class Intro(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    intro_name = models.CharField(max_length=100)
    intro = models.TextField(blank=True)
    presentation = models.TextField(blank=True)

    github_link = models.TextField(blank=True)
    insta_link = models.TextField(blank=True)
    linked_in_link = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)

    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    my_photo = models.ImageField(upload_to=f'photos/{intro_name}', verbose_name='Img', blank=True)

    def __str__(self):
        return self.intro_name

    class Meta:
        ordering = ['-intro_name']

    def get_absolute_url(self):
        return reverse('intro',kwargs={"slug":self.slug})

###########################CV################################
class Language(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    lang = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    lang_percent = models.IntegerField(default=0,verbose_name='lang_percent', validators=[MinValueValidator(0),
                                       MaxValueValidator(100)])
    def __str__(self):
        return self.lang

    class Meta:
        ordering = ['lang_percent']
    def get_absolute_url(self):
        return reverse('language',kwargs={"slug":self.slug})

class Skill(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    skill = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    skill_percent = models.IntegerField(default=0,verbose_name='lang_percent')
    def __str__(self):
        return self.skill

    class Meta:
        ordering = ['skill_percent']

    def get_absolute_url(self):
        return reverse('skill',kwargs={"slug":self.slug})

class Experience(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    years = models.CharField(max_length=100)
    ordering_rate = models.IntegerField(default=1, verbose_name='ordering', validators=[MinValueValidator(1),
                                                                                        MaxValueValidator(100)])

    company = models.CharField(max_length=200)
    description = models.TextField(blank=False)
    position = models.CharField(max_length=200)

    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Published')


    def __str__(self):
        return self.years

    class Meta:
        ordering = ['-years']

    def get_absolute_url(self):
        return reverse('experience',kwargs={"slug":self.slug})


class Certificate(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    certificate_name = models.CharField(max_length=200)
    date_obtained = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=True)
    certificate_link = models.TextField(blank=True)
    certificate_photo = models.ImageField(upload_to=f'photos/{certificate_name}', verbose_name='Img', blank=True)

class Education(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    years = models.CharField(max_length=100, blank=False)
    degree = models.CharField(max_length=200, blank=False)
    establishment = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    meta_desc = models.CharField(max_length=160, blank=True)
    meta_keys = models.CharField(max_length=300, blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Published')


    def __str__(self):
        return self.years

    class Meta:
        ordering = ['-years']

    def get_absolute_url(self):
        return reverse('education',kwargs={"slug":self.slug})



class Interests(models.Model):
    page_lang = models.CharField(max_length=10, choices=page_language_choices, blank=False,
                                 verbose_name='LANGUAGE:', default='ENG')
    interest = models.CharField(max_length=100)
    slug = models.SlugField(max_length=255, verbose_name='url', unique=True)
    icon = models.CharField(max_length=1000)
    def __str__(self):
        return self.interest

    class Meta:
        ordering = ['interest']

    def get_absolute_url(self):

portfolio/portfolio_landing/forms.py
from django import forms
from django.core.exceptions import ValidationError
import re




class EmailForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'First Name'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Last Name'}))
    mail = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Contact E-mail'}))
    mobile_number = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Mobile Number'}))
    message_text = forms.CharField(required=True, widget=forms.Textarea(attrs={'placeholder':'Message'})) #'readonly': True}))
    # fields=['driver_pk', 'column_numb



class SendChatForm(forms.Form):
    fields = ['name', 'telephone', 'message']
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Name'}))
    telephone = forms.CharField(required=True, max_length=20 , widget=forms.TextInput(attrs={'placeholder':'Mobile Number'}))
    message = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder':'Message'}))
    def clean_telephone(self):
        telephone = self.cleaned_data['telephone']
        if re.match(r'^\+?1?\d{9,15}$', telephone):
            return telephone
        else:
            raise ValidationError('Format: +9999999999, max: 15 characters')

portfolio/portfolio_landing/templates/portfolio_landing/CV.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="view-port" content="width=device-width, initial-scale=1.0">
    <title>Personal Portfolio</title>
    <link rel="stylesheet" href="{% static 'cvstyle.css' %} " />

    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.4-web/css/all.css' %} ">
    <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.4-web/css/brands.css' %} ">





</head>
<body>
<div class="container">
    <div class="left_Side">
        <div class="profileText">
            <div class="imgBx">

                {% if selected_cv.0.my_cv_photo %}
                <img src="{{ selected_cv.0.my_cv_photo.url }}">
                {% else %}
                <img src="{% static 'images/cv.JPG'%}">
                {% endif %}

            </div>
            <h2>{{ selected_cv.0.mycvname }}<br><span>{{ selected_cv.0.myprofile }}</span></h2>

        </div>
        <div class="contactInfo">
            <h3 class="title">Contact Info</h3>
            <ul>
                <li>
                    <span class="icon"><i class="fa fa-envelope"></i></span>
                    <a href="mailto: {{ selected_cv.0.cvmail }}"><span class="text">{{ selected_cv.0.cvmail }}</span></a>
                </li>

                <li>
                    <span class="icon"><i class="fa fa-globe"></i></span>
                    <a href="{{ selected_cv.0.cvwebsite }}"><span class="text">{{ selected_cv.0.cvwebsite }}</span></a>
                </li>

                <li>
                    <span class="icon"><i class="fa fa-address-card"></i></span>
                    <a href="{{ selected_cv.0.cvlinkedin }}"><span class="text">www.linkedin.com</span></a>
                </li>



                <li>
                    <span class="icon"><i class="fa-regular fa-map"></i></span>
                    <span class="text">{{ selected_cv.0.cvlocation }}</span>
                </li>

            </ul>
        </div>

        <div class="contactInfo language">
            {% if language_set %}
            <h3 class="title">Languages</h3>
            <ul>{% for item in language_set %}
                <li>
                    <span class="text">{{ item.lang }}</span>
                    <div class="percent">
                         <div style="width: {{ item.lang_percent }}%;"></div>
                     </div>
                </li>
                {% endfor %}
            </ul>
             {% endif %}
        </div>


        <div class="contactInfo education">
            {% if education_set %}
            <h3 class="title">Education</h3>
            <ul>
                {% for item in education_set %}
                <li>
                    <h5>{{ item.years }}</h5>
                    <h4>{{ item.degree }}</h4>
                    <h4>{{ item.description }}</h4>
                    <h4>{{ item.establishment }}</h4>
                </li>
                {% endfor %}

            </ul>
            {% endif %}
        </div>



    </div>
    <div class="right_Side">

        <div class="about">
            <h2 class="title2">Profile</h2>
            <p>
                {{ selected_cv.0.description }}
            </p>
        </div>
        <div class="about">
            {% if experience_set %}
            <h2 class="title2">Experience</h2>
            {% for item in experience_set %}
            <div class="box">
                <div class="year_company">
                    <h5>{{ item.years }}</h5>
                    <h5>{{ item.company }}</h5>
                </div>
                <div class="text">
                    <h4>
                        {{ item.position }}
                    </h4>
                    <p>
                       {{ item.description }}

                    </p>
                </div>
            </div>
                {% endfor %}
                {% endif %}
        </div>



        <div class="about skills">
            {% if skill_set %}
            <h2 class="title2">Professional Skills</h2>
            {% for item in skill_set %}
            <div class="box">
                <h4>{{ item.skill }}</h4>
                <div class="percent">
                    <div style="width:{{ item.skill_percent }}%"></div>
                </div>
            </div>
            {% endfor %}
            {% endif %}

        </div>

        <div class="about interest">
            {% if interest_set %}
             <h2 class="title2">Interest</h2>
            <ul>
                {% for item in interest_set %}
                <li><i class="fa {{ item.icon }}"></i> {{ item.interest }}</li>
                {% endfor %}

            </ul>
            {% endif %}

        </div>





    </div>

</div>
</body>
</html>

portfolio/portfolio_landing/templates/portfolio_landing/email_status.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" name="view-port" content="width=device-width, initial-scale=1.0">
    <title>Personal Portfolio</title>

    <link rel="stylesheet" href="{% static 'style.css' %} " />

</head>
<body>
<div class="toggle" onclick="toggleMenu()"></div>

<section class="about" id="about">

    <div class="title white">
        <h2>Email</h2>
        <p>
            {{ email_status }}
        </p>
    </div>
    <div class="content">
        <div class="textBx1">
            <p>

            </p>
        </div>
        <div class="imgBx">
            <img src="{% static 'images/email.png' %}"  width="50px;">

        </div>

    </div>
</section>


<div class="sidebar">

<ul class="menu">
    <li><a href="{% url 'index' %}" onclick="toggleMenu();">Home</a></li>

</ul>

</div>
<script>
    function toggleMenu(){
    const menuToggle = document.querySelector('.toggle');
    const sidebar = document.querySelector('.sidebar');
    menuToggle.classList.toggle('active');
    sidebar.classList.toggle('active');
    }
</script>

</body>
</html>